"""SkillPod package entry."""

from skillpod.shared.config import Config
from skillpod.shared import exceptions
from skillpod.modules import (
    search_skills,
    load_skill,
    add_skill,
    remove_skill,
    list_skills,
    read_skill_file,
    validate_skill,
    SkillSummary,
    SkillDetail,
    FileContent,
    SearchResult,
    AddResult,
    RemoveResult,
    ListResult,
    ValidationIssue,
    ValidationResult,
    build_index,
    should_reindex,
    index_search,
    get_by_id,
    list_all,
    IndexBuildResult,
    ReindexDecision,
)

__all__ = [
    "Config",
    "exceptions",
    "search_skills",
    "load_skill",
    "add_skill",
    "remove_skill",
    "list_skills",
    "read_skill_file",
    "validate_skill",
    "SkillSummary",
    "SkillDetail",
    "FileContent",
    "SearchResult",
    "AddResult",
    "RemoveResult",
    "ListResult",
    "ValidationIssue",
    "ValidationResult",
    "build_index",
    "should_reindex",
    "index_search",
    "get_by_id",
    "list_all",
    "IndexBuildResult",
    "ReindexDecision",
]
